### PR TITLE
Update GlobalSuppressions.cs

### PR DESCRIPTION
**Pull request by naitp**
Addresses issue found in https://github.com/Microsoft/ILMerge/issues/1 (Can't compile the code because of Chinese letters).

### CODE REVIEW

**Comment by mike-barnett** [comment]
Thanks so much! I don't know how that bad byte got in there. However, did you do something that would have committed the file *without* windows line endings (\r\n)? That appeared to be the case when I pulled the merged file. I just committed a version with the line endings renormalized to Windows line endings.

**Comment by dmetzgar** [comment]
That byte comes from encoding. If you use UTF instead of ASCII.

**Comment by mike-barnett** [comment]
What I meant is that none of the other files in that directory have the byte-encoding byte, so I don't know why that file would have it.

**Comment by naitp** [comment]
Regarding line endings, the only thing I can think of is that the ACE Editor converted them inadvertently when I saved the file (see last comment here: https://github.com/gitlabhq/gitlabhq/issues/3982 from Nov. 2016), but I can't seem to duplicate the issue on any of my repos.  Sorry I couldn't be more help with this one.  I'll try to duplicate it when I have some more time (when I'm not at work).

**Comment by mike-barnett** [comment]
No worries! I was just mentioning it because I thought I had put the right magic goo in .gitattributes so that Git would always put in the Windows line endings. I guess line endings and the great tab vs. spaces debate will always be among the great religious battles of the world...

**Pull request merged**
